### ISSUE TITLE
`A2-10-1`: Exclude variable templates

### ISSUE THREAD

**Issue by lcartey** [github/codeql-coding-standards#214]
### Affected rules
 - `A2-10-1`

### Description

Variable templates can cause name duplication across scopes. The simplest option would be to exclude variable templates all together from this rule.

In addition, the example shows two variable templates in the same scope - is that something we actually report? The rule should only report issues from inner/outer scope pairs.

### Example

```cpp
template <typename Foo>
constexpr bool foo = false;
template <T>
constexpr bool foo<T> = true;
```

**Comment by knewbury01** [comment]
aha! both things described above were causing issues-

the rule was previously [including variables in the same scope](https://github.com/github/codeql-coding-standards/blob/main/cpp/common/src/codingstandards/cpp/Scope.qll#L125), not just ones in inner/outer pairs as described in the rule

I have been a bit cautious in how I added to the scope lib to address this, (added predicates for this case, as opposed to refactored - because other queries seem to rely on the `hides` predicate as is), but lmk if that makes sense or not to do
