### ISSUE TITLE
`M9-3-3`: Identify indirect assignment of member data

### ISSUE THREAD

**Issue by lcartey** [github/codeql-coding-standards#381]
### Affected rules
 - `M9-3-3`

### Description

Improve the rule to detect assignment into references or pointers into member data.

### Example
In this example we see a member function which modifies a member variable called `values_`, by iterating through and taking a reference to each element.

```cpp
template <typename U = T>
void fill(const T& val) {
    for (auto& elem : values_) {
      elem = val;
    }
  }
```

**Comment by lcartey** [comment]
Another example:
```cpp
constexpr T& front() noexcept { return values_[0]; }
```

**Comment by knewbury01** [comment]
the original issue reported here was related to templates, and was fixed in a [previous issue](https://github.com/github/codeql-coding-standards/commit/2029a18c4711341ea1f8ffdccea6ea14e66661ba)

but the second example `constexpr int &front() noexcept { return values[0]; } // COMPLIANT` was due to a logic omission
