### ISSUE TITLE
`A7-1-3`: Triggered on `static_cast`

### ISSUE THREAD

**Issue by nbusser** [github/codeql-coding-standards#601]
### Affected rules
 - A7-1-3

### Description

For some reason, `A7-1-3` is triggered on basic varibales created from `static_cast`

### Example
```cpp
void false_positive() {
    std::uint8_t u8{0};

    auto const u32 = static_cast<std::uint32_t>(u8); // Triggers A7-1-3 warning
    std::uint32_t const u32b = static_cast<std::uint32_t>(u8); // Triggers A7-1-3 warning

    const auto u32c = static_cast<std::uint32_t>(u8); // Triggers A7-1-3 warning
    const std::uint32_t u32d = static_cast<std::uint32_t>(u8); // Triggers A7-1-3 warning
}
```

**Comment by lcartey** [comment]
Thanks for this report!

The following cases are false positives:
```cpp
    auto const u32 = static_cast<std::uint32_t>(u8); // Triggers A7-1-3 warning
    std::uint32_t const u32b = static_cast<std::uint32_t>(u8); // Triggers A7-1-3 warning

    const auto u32c = static_cast<std::uint32_t>(u8); // Triggers A7-1-3 warning
```
These are reported because we confuse the use of `std::uint32_t` in the cast with the potential use of `std::uint_t` in the variable declaration type. This can be adjusted.

The final case is interesting:
```cpp
    const std::uint32_t u32d = static_cast<std::uint32_t>(u8); // Triggers A7-1-3 warning
```
`std::uint32_t` is a typedef, and the rule for A7-1-3 states:
> CV-qualifiers shall be placed on the right hand side of the type that is a typedef or a using name.

So, strictly speaking this is a true positive. However, the rule contradicts itself, because it later gives this example as compliant:
```cpp
void Fn(const std::uint8_t& input) // Compliant
```
I don't know whether they just forgot `std::uint8_t` was a typedef, or they intended to suggest an exclusion for standard library types, but it's not clear called out. For now, we're sticking with the strict definition of the rule.

**Comment by nbusser-sr** [comment]
Interesting! Thanks for the feedback
