### ISSUE TITLE
`A7-1-7`: Exclude anonymous structs

### ISSUE THREAD

**Issue by lcartey** [github/codeql-coding-standards#630]
### Affected rules
 - `A7-1-7`

### Description

Anonymous structs are considered a type declaration in our database, but they are usually combined with other declarations by necessity (otherwise it is impossible to later refer to the struct). We should therefore exclude such anonymous structs from the query.

### Example

```cpp
typedef struct x { int y }; z;
```

**Comment by knewbury01** [comment]
dont actually think that this example has anything labelled anonymous (in the database or otherwise)

for example: 
```
// clang-format off
typedef struct x { int y; } z; //COMPLIANT
// clang-format on

struct OuterStruct {
  struct {
    int val[10]; // COMPLIANT
  } firstArray;

  struct {
    int val[10][2]; // COMPLIANT
  } secondArray;
};
```

run with:
```
from Declaration d
where d.(UserType).isAnonymous()
select d
```
shows only the nested structs (and the definition of anonymous [here](https://learn.microsoft.com/en-us/cpp/cpp/anonymous-class-types?view=msvc-170) suggests that unnamed structs only are anon) - the struct example in the report has a name

this still has the typedef problem though, so I think what we want here is actually to omit cases where `TypeDeclarationEntry`'s exist on the same line? (the declaration of z is on the same line as the definition of x)

this will still yield an alert for the definition of y though, and not sure if we want to then begin permitting structs to generally be defined on one line . I think not, so I will only only omit the extra alerts from the typedef related pieces
